GET http://localhost:8080/example?id=InitialId


###
POST http://localhost:8080/example/
Content-Type: application/json
Accept: application/json

{
  "entityToAdd" : "valid"
}

###
POST http://localhost:8080/example/
Content-Type: application/json
Accept: application/json

{
  "entityToAdd" : "invalid"
}